
[functions.check-nft-conditions]
enabled = true
verify_jwt = true
import_map = "./functions/check-nft-conditions/deno.json"
entrypoint = "./functions/check-nft-conditions/index.ts"

[functions.nft-metadata]
enabled = true
verify_jwt = true
import_map = "./functions/nft-metadata/deno.json"
entrypoint = "./functions/nft-metadata/index.ts"

[functions.player-write]
enabled = true
verify_jwt = false
entrypoint = "./functions/player-write/index.ts"

[functions.approve-run]
enabled = true
verify_jwt = false
entrypoint = "./functions/approve-run/index.ts"

[functions.issue-seed]
enabled = true
verify_jwt = false
entrypoint = "./functions/issue-seed/index.ts"
